spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.66.100:3306/xingtaomall_pms
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848


  application:
    name: xingtaomall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.66.100


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


server:
  port: 9999
logging:
  level:
    com.xingtao.xingtaomall: debug
